app = "spurs-book-value"
primary_region = "lhr"

[build]

[env]
  PUBLIC_MODE = "1"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"
